### ISSUE TITLE
Deploying into k8s cluster

### ISSUE THREAD

**Issue by hicotton02** [ai-dock/stable-diffusion-webui#25]
I am using this docker image to deploy into a k8s cluster.  When I access the service through the LB (192.168.1.36:7860) I get redirected to http://localhost:1111/login but since I am accessing externally, that doesnt work. I have an ollama implementation and a open-webui implementation in the same k8s cluster that I am trying to connect to. What am I missing?

here is my deployment yaml:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: automatic1111
  namespace: ollama
  labels:
    app: automatic1111
spec:
  replicas: 1
  selector:
    matchLabels:
      app: automatic1111
  template:
    metadata:
      labels:
        app: automatic1111
    spec:
      containers:
      - name: automatic1111-container
        image: ghcr.io/ai-dock/stable-diffusion-webui:latest
        ports:
        - containerPort: 7860
        resources:
          limits:
            nvidia.com/gpu: 1
            memory: "16Gi"
            cpu: "8"
          requests:
            nvidia.com/gpu: 1
            memory: "16Gi"
            cpu: "8"
        env:
        - name: SERVICEPORTAL_HOME
          value: "http://192.168.1.36:7860"
        - name: SERVICEPORTAL_LOGIN
          value: "http://192.168.1.36:7860/login"
        - name: PORT
          value: "7860"
        volumeMounts:
        - name: models-volume
          mountPath: /models
      volumes:
      - name: models-volume
        persistentVolumeClaim:
          claimName: automatic1111-models-pvc
      nodeSelector:
        ollama-gpu: "true"
```
I am setting the serviceportal ip manually in the deployment file, but when the pod starts:
```
root@master1:~# kubectl exec -it automatic1111-d4bf6556-7vlxs -n ollama -- /bin/bash
(webui) root@automatic1111-d4bf6556-7vlxs:/opt# printenv | grep SERVICEPORTAL
SERVICEPORTAL_VENV_PIP=/opt/environments/python/serviceportal/bin/pip
SERVICEPORTAL_VENV=/opt/environments/python/serviceportal
SERVICEPORTAL_VENV_PYTHON=/opt/environments/python/serviceportal/bin/python
SERVICEPORTAL_LOGIN=http://localhost:1111/login
SERVICEPORTAL_HOME=http://localhost:1111
```

I have also tried manually editing the caddy/share/*_config_* files to try and push the config change to no avail.

**Comment by robballantyne** [comment]
`WEB_ENABLE_AUTH=false` if it's safe to do so is the easiest method.
Alternative is to coordinate `WEB_TOKEN`s and pass as Authorisation (Bearer) headers.

This isn't a use case I'd intended for the container but would be interested in hearing about your results

**Comment by hicotton02** [comment]
that worked. I am running it internally and do not need web auth.
auto1111-deployment.yaml:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: automatic1111
  namespace: ollama
  labels:
    app: automatic1111
spec:
  replicas: 1
  selector:
    matchLabels:
      app: automatic1111
  template:
    metadata:
      labels:
        app: automatic1111
    spec:
      containers:
      - name: automatic1111-container
        image: ghcr.io/ai-dock/stable-diffusion-webui:latest
        ports:
        - containerPort: 7860
        resources:
          limits:
            nvidia.com/gpu: 1
            memory: "64Gi"
            cpu: "12"
          requests:
            nvidia.com/gpu: 1
            memory: "64Gi"
            cpu: "12"
        env:
        - name: WEB_ENABLE_AUTH
          value: "false"
        - name: PORT
          value: "7860"
        - name: WEBUI_ARGS
          value: "--api --listen"
        volumeMounts:
        - name: models-volume
          mountPath: /opt/stable-diffusion-webui/models
      volumes:
      - name: models-volume
        persistentVolumeClaim:
          claimName: automatic1111-models-pvc
      nodeSelector:
        ollama-gpu: "true"
```
auto1111-svc.yaml
```
apiVersion: v1
kind: Service
metadata:
  name: automatic1111-service
  namespace: ollama
spec:
  selector:
    app: automatic1111
  ports:
    - protocol: TCP
      port: 7860  # External port you want to use
      targetPort: 7860  # Port on the pod where Automatic 1111 is listening
  type: LoadBalancer
```
auto1111-pvc.yaml
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: automatic1111-models-pvc
  namespace: ollama
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi  # Adjust based on your needs
```
