### ISSUE TITLE
Running Locally : Torch is not able to use GPU

### ISSUE THREAD

**Issue by FyzzLive** [ai-dock/stable-diffusion-webui#5]
Running Locally : Torch is not able to use GPU
Pulled the repo, edited the env, added my own provisioning script, and ran `docker compose up`
Received this error after the build process as it was starting:docker
`RuntimeError: Torch is not able to use GPU; add --skip-torch-cuda-test to COMMANDLINE_ARGS variable to disable this check`

**Comment by zxcjhg** [comment]
just add `runtime: nvidia` to the docker-compose.yaml

**Comment by FyzzLive** [comment]
Now getting `services.runtime must be a mapping`
```yaml
    #docker-compose.yaml
    runtime: nvidia
    environment:
        # Don't enclose values in quotes
        - DIRECT_ADDRESS=${DIRECT_ADDRESS:-127.0.0.1}
        - DIRECT_ADDRESS_GET_WAN=${DIRECT_ADDRESS_GET_WAN:-false}
        ...
```
